apiVersion: v1
kind: ReplicationController
metadata:
  name: angularfrontend-rc
spec:
  replicas: 2
  selector:
    app: angularfrontend
  template: 
    metadata:
      labels:
        app: angularfrontend
        tier: frontend
    spec:
      containers:
      - name: angularfrontend
        image: dynatrace//easytravel-angular-frontend
        env:
        - name: ET_BACKEND_URL
          value: "http://backend:8080"
        ports:
        - containerPort: 8080
        - containerPort: 8280